require "../spec_helper"

# `Oas.parse_file` turns an OpenAPI/Swagger document into requests. Everything in the file is
# written by hand or generated by someone else's tool, so every failure here has to arrive as a
# `Gori::Error` — that is the only class `Import.import_file` passes through cleanly and the
# only one `CLI.run` turns into a message instead of a backtrace.
private def with_spec(body : String, ext : String, &)
  path = File.tempname("gori-oas", ext)
  File.write(path, body)
  begin
    yield path
  ensure
    File.delete?(path)
  end
end

describe Gori::Import::Oas do
  it "imports an ordinary spec" do
    body = <<-YAML
      openapi: 3.0.0
      info: {title: t, version: "1"}
      servers:
        - url: "https://api.example.test/v1"
      paths:
        /a:
          get:
            responses: {"200": {description: ok}}
      YAML
    with_spec(body, ".yaml") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.size.should eq(1)
    end
  end

  # `URI.parse` RAISES on a port an author can type by hand: one that overflows Int32 comes
  # back as `OverflowError`, a non-numeric one as `URI::Error`. Neither is a `Gori::Error`, so
  # both left `server_base` as a raw backtrace out of the CLI.
  it "names an unparseable servers[0].url instead of raising out of the importer" do
    ["https://api.example.test:99999999999999999999/v1", "https://api.example.test:abc/v1"].each do |url|
      body = <<-YAML
        openapi: 3.0.0
        info: {title: t, version: "1"}
        servers:
          - url: "#{url}"
        paths:
          /a:
            get:
              responses: {"200": {description: ok}}
        YAML
      with_spec(body, ".yaml") do |path|
        expect_raises(Gori::Error, /unparseable/) { Gori::Import::Oas.parse_file(path) }
      end
    end
  end

  # The YAML parses; the `to_json` in the same expression is what raises. A self-referential
  # anchor is legal YAML and yields a CYCLIC `YAML::Any`, which `to_json` walks until it hits
  # the stdlib's nesting guard — a `JSON::Error`, which the `YAML::ParseException` clause
  # never covered.
  it "reports a self-referential YAML anchor instead of crashing on the cycle" do
    with_spec("a: &anchor\n  b: *anchor\n", ".yaml") do |path|
      expect_raises(Gori::Error, /cannot be represented as JSON/) { Gori::Import::Oas.parse_file(path) }
    end
  end

  # `.inf` and `.nan` are legal YAML scalars an OpenAPI author writes by hand (`maximum: .inf`
  # in a schema is ordinary) and a deep-but-ACYCLIC spec trips the same nesting guard, so all
  # three arrive as `JSON::Error` too. The clause must not send the operator hunting for an
  # anchor that does not exist.
  it "does not blame an anchor for a value that merely has no JSON spelling" do
    {"maximum: .inf\n", "maximum: .nan\n"}.each do |body|
      with_spec(body, ".yaml") do |path|
        ex = expect_raises(Gori::Error, /cannot be represented as JSON/) { Gori::Import::Oas.parse_file(path) }
        ex.message.to_s.should_not contain("self-referential anchor (an alias")
      end
    end
  end

  it "still reports ordinary malformed YAML as bad YAML" do
    with_spec("openapi: [unclosed\n", ".yaml") do |path|
      expect_raises(Gori::Error, /not valid YAML/) { Gori::Import::Oas.parse_file(path) }
    end
  end
end
