require "../spec_helper"

# `Oas.parse_file` turns an OpenAPI/Swagger document into requests. Everything in the file is
# written by hand or generated by someone else's tool, so every failure here has to arrive as a
# `Gori::Error` — that is the only class `Import.import_file` passes through cleanly and the
# only one `CLI.run` turns into a message instead of a backtrace.
private def with_spec(body : String, ext : String, &)
  path = File.tempname("gori-oas", ext)
  File.write(path, body)
  begin
    yield path
  ensure
    File.delete?(path)
  end
end

describe Gori::Import::Oas do
  it "imports an ordinary spec" do
    body = <<-YAML
      openapi: 3.0.0
      info: {title: t, version: "1"}
      servers:
        - url: "https://api.example.test/v1"
      paths:
        /a:
          get:
            responses: {"200": {description: ok}}
      YAML
    with_spec(body, ".yaml") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.size.should eq(1)
    end
  end

  it "resolves local parameter, requestBody, and schema refs at path and operation level" do
    body = <<-JSON
      {
        "openapi": "3.0.3",
        "info": {"title": "t", "version": "1"},
        "servers": [{"url": "http://api.example.test/v1"}],
        "components": {
          "parameters": {
            "UserId": {"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}},
            "ApiVer": {"name": "api_version", "in": "query", "required": true, "schema": {"type": "string"}}
          },
          "requestBodies": {
            "User": {"required": true, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/User"}}}}
          },
          "schemas": {"User": {"type": "object"}, "UserList": {"type": "array"}}
        },
        "paths": {
          "/users/{id}": {
            "parameters": [{"$ref": "#/components/parameters/UserId"}],
            "get": {
              "parameters": [{"$ref": "#/components/parameters/ApiVer"}],
              "responses": {"200": {"description": "ok"}}
            },
            "put": {
              "requestBody": {"$ref": "#/components/requestBodies/User"},
              "responses": {"200": {"description": "ok"}}
            }
          },
          "/users": {
            "post": {
              "requestBody": {"content": {"application/json": {"schema": {"$ref": "#/components/schemas/UserList"}}}},
              "responses": {"200": {"description": "ok"}}
            }
          }
        }
      }
      JSON

    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.size.should eq(3)
      get = String.new(result.flows[0].request.head)
      put = String.new(result.flows[1].request.head)
      get.should contain("GET /v1/users/1?api_version=api_version HTTP/1.1")
      put.should contain("PUT /v1/users/1 HTTP/1.1")
      put.should contain("Content-Type: application/json\r\n")
      String.new(result.flows[1].request.body.not_nil!).should eq("{}")
      String.new(result.flows[2].request.body.not_nil!).should eq("[]")
    end
  end

  it "imports Swagger 2 host, basePath, body, formData, and consumes" do
    body = <<-JSON
      {
        "swagger": "2.0",
        "info": {"title": "t", "version": "1"},
        "host": "127.0.0.1:18501",
        "basePath": "/v1",
        "schemes": ["http"],
        "consumes": ["application/json"],
        "definitions": {"Payload": {"type": "object"}},
        "paths": {
          "/users/{id}": {
            "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
            "post": {
              "parameters": [{"name": "body", "in": "body", "schema": {"$ref": "#/definitions/Payload"}}],
              "responses": {"200": {"description": "ok"}}
            }
          },
          "/form": {
            "post": {
              "consumes": ["application/x-www-form-urlencoded"],
              "parameters": [{"name": "name", "in": "formData", "required": true, "type": "string"}],
              "responses": {"200": {"description": "ok"}}
            }
          },
          "/upload": {
            "post": {
              "consumes": ["multipart/form-data"],
              "parameters": [{"name": "file", "in": "formData", "required": true, "type": "file"}],
              "responses": {"200": {"description": "ok"}}
            }
          }
        }
      }
      JSON

    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.size.should eq(3)
      request = String.new(result.flows[0].request.head)
      request.should contain("POST /v1/users/1 HTTP/1.1")
      request.should contain("Host: 127.0.0.1:18501\r\n")
      request.should contain("Content-Type: application/json\r\n")
      String.new(result.flows[0].request.body.not_nil!).should eq("{}")
      form_head = String.new(result.flows[1].request.head)
      form_head.should contain("Content-Type: application/x-www-form-urlencoded\r\n")
      String.new(result.flows[1].request.body.not_nil!).should eq("name=name")
      upload_head = String.new(result.flows[2].request.head)
      upload_head.should contain("Content-Type: multipart/form-data; boundary=gori-openapi-boundary\r\n")
      String.new(result.flows[2].request.body.not_nil!).should contain("filename=\"file\"")
    end
  end

  it "reports remote refs without fetching them" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.example.test"}],"paths":{"/a":{"get":{
         "parameters":[{"$ref":"https://example.test/parameters.json#/Token"}],
         "responses":{"200":{"description":"ok"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      expect_raises(Gori::Error, /remote.*\$ref|\$ref.*remote/i) { Gori::Import::Oas.parse_file(path) }
    end
  end

  it "bounds local ref cycles and counts the affected operation as skipped" do
    body = <<-JSON
      {"openapi":"3.0.3","info":{"title":"t","version":"1"},
       "servers":[{"url":"https://api.example.test"}],
       "components":{"parameters":{"A":{"$ref":"#/components/parameters/B"},
                                     "B":{"$ref":"#/components/parameters/A"}}},
       "paths":{"/a":{"get":{"parameters":[{"$ref":"#/components/parameters/A"}],
         "responses":{"200":{"description":"ok"}}}}}}
      JSON
    with_spec(body, ".json") do |path|
      result = Gori::Import::Oas.parse_file(path)
      result.flows.should be_empty
      result.skipped.should eq(1)
    end
  end

  # `URI.parse` RAISES on a port an author can type by hand: one that overflows Int32 comes
  # back as `OverflowError`, a non-numeric one as `URI::Error`. Neither is a `Gori::Error`, so
  # both left `server_base` as a raw backtrace out of the CLI.
  it "names an unparseable servers[0].url instead of raising out of the importer" do
    ["https://api.example.test:99999999999999999999/v1", "https://api.example.test:abc/v1"].each do |url|
      body = <<-YAML
        openapi: 3.0.0
        info: {title: t, version: "1"}
        servers:
          - url: "#{url}"
        paths:
          /a:
            get:
              responses: {"200": {description: ok}}
        YAML
      with_spec(body, ".yaml") do |path|
        expect_raises(Gori::Error, /unparseable/) { Gori::Import::Oas.parse_file(path) }
      end
    end
  end

  # The YAML parses; the `to_json` in the same expression is what raises. A self-referential
  # anchor is legal YAML and yields a CYCLIC `YAML::Any`, which `to_json` walks until it hits
  # the stdlib's nesting guard — a `JSON::Error`, which the `YAML::ParseException` clause
  # never covered.
  it "reports a self-referential YAML anchor instead of crashing on the cycle" do
    with_spec("a: &anchor\n  b: *anchor\n", ".yaml") do |path|
      expect_raises(Gori::Error, /cannot be represented as JSON/) { Gori::Import::Oas.parse_file(path) }
    end
  end

  # `.inf` and `.nan` are legal YAML scalars an OpenAPI author writes by hand (`maximum: .inf`
  # in a schema is ordinary) and a deep-but-ACYCLIC spec trips the same nesting guard, so all
  # three arrive as `JSON::Error` too. The clause must not send the operator hunting for an
  # anchor that does not exist.
  it "does not blame an anchor for a value that merely has no JSON spelling" do
    {"maximum: .inf\n", "maximum: .nan\n"}.each do |body|
      with_spec(body, ".yaml") do |path|
        ex = expect_raises(Gori::Error, /cannot be represented as JSON/) { Gori::Import::Oas.parse_file(path) }
        ex.message.to_s.should_not contain("self-referential anchor (an alias")
      end
    end
  end

  it "still reports ordinary malformed YAML as bad YAML" do
    with_spec("openapi: [unclosed\n", ".yaml") do |path|
      expect_raises(Gori::Error, /not valid YAML/) { Gori::Import::Oas.parse_file(path) }
    end
  end
end
