require "../spec_helper"

include Gori::Tui

# Mouse tracking must be OFF for the duration of an `$EDITOR` shell-out.
#
# `Runner#run_external_editor` handed the child the same tty via `Process::Redirect::Inherit`
# and suspended through the vendored termisu fork, whose `Terminal#with_mode`
# (lib/termisu/src/termisu/terminal.cr:505-541) exits the alternate screen but never calls
# `disable_mouse`. Measured on a live editor session with tmux pane flags: `alternate_on=0`
# while `mouse_any_flag=1` and `mouse_sgr_flag=1`. A click or a scroll therefore landed in the
# EDITOR's stdin as an SGR report (`\e[<0;40;12M`), and for `ExternalEditor::WIRE_KINDS`
# (:request, :intercept) whatever the editor saves becomes the operator's wire bytes — gori
# would send bytes nobody typed.
#
# `lib/` is regenerated by `shards install`, so the fix is gori-side:
# `Runner.suspend_without_mouse` brackets the suspend. `term` is unrestricted there precisely
# so this recorder can drive it — the Runner needs a live tty and cannot be instantiated.

private class TermSpy
  getter log = [] of Symbol

  def disable_mouse : Nil
    @log << :disable
  end

  def enable_mouse : Nil
    @log << :enable
  end

  # Stands in for `Termisu#suspend`: the window during which the child owns the tty.
  def suspend(&) : Nil
    @log << :suspend_in
    yield
    @log << :suspend_out
  end
end

describe "Runner.suspend_without_mouse" do
  it "disables the mouse BEFORE the child owns the tty and restores it after" do
    spy = TermSpy.new
    Runner.suspend_without_mouse(spy, mouse: true) { spy.log << :editor }
    # Ordering is the whole contract: :disable must precede :suspend_in, or the child still
    # sees SGR reports for the first frames, and :enable must follow :suspend_out.
    spy.log.should eq([:disable, :suspend_in, :editor, :suspend_out, :enable])
  end

  it "honours Mouse=off — it restores what the operator set, it does not force it on" do
    spy = TermSpy.new
    Runner.suspend_without_mouse(spy, mouse: false) { spy.log << :editor }
    spy.log.should eq([:disable, :suspend_in, :editor, :suspend_out])
  end

  it "restores through a RAISING editor, so a bad $EDITOR can't cost the session its mouse" do
    spy = TermSpy.new
    expect_raises(Exception, "no such editor") do
      Runner.suspend_without_mouse(spy, mouse: true) { raise "no such editor" }
    end
    spy.log.should eq([:disable, :suspend_in, :enable]) # the ensure ran; :suspend_out never did
  end
end
